<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class AlertRule extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'description',
        'type', // metric, status, software
        'metric', // cpu_usage, memory_usage, disk_usage
        'condition', // >, <, =, >=, <=, change
        'threshold',
        'duration_minutes',
        'severity', // info, warning, critical
        'lab_id',
        'notification_channels', // array
        'is_active',
    ];

    protected $casts = [
        'threshold' => 'float',
        'duration_minutes' => 'integer',
        'notification_channels' => 'array',
        'is_active' => 'boolean',
    ];

    /**
     * Get the lab that owns the alert rule.
     */
    public function lab(): BelongsTo
    {
        return $this->belongsTo(Lab::class);
    }

    /**
     * Get the alerts generated by this rule.
     */
    public function alerts(): HasMany
    {
        return $this->hasMany(Alert::class);
    }
}
